# Generated by Django 4.0.1 on 2022-01-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('responsible', models.CharField(max_length=50)),
                ('documentfile_url', models.CharField(max_length=50)),
            ],
        ),
    ]
