# Generated by Django 4.0.1 on 2022-02-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamverwaltung_main', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
