# Generated by Django 4.0.4 on 2022-04-15 10:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamverwaltung_main', '0003_project_isactive_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('s_num', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(code='invalid s_num', message='s-nummer nach folgendem Schema angeben: s12345', regex='^s[0-9]{5}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='teamverwaltung_main.student')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_wing', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RoleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveBigIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamverwaltung_main.role')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamverwaltung_main.poll')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveBigIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamverwaltung_main.project')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamverwaltung_main.poll')),
            ],
        ),
    ]
