# Generated by Django 4.0.4 on 2022-05-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamverwaltung_main', '0007_sectioncontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='abbreviation',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
