# Generated by Django 4.0.4 on 2022-05-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamverwaltung_main', '0006_rename_name_student_last_name_student_faculty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
                ('activated', models.BooleanField()),
            ],
        ),
    ]
