= Use-Case Model: {project-name}
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Allgemeine Informationen
Die Anordnung der Use Cases entspricht der Priorisierung in der Entwicklung.


Da es sich hier um eine Weiterentwicklung eines bereits bestehenden Online-Tools handelt, haben wir Use Cases identifiziert, die bereits implementiert wurden. Auf Grund dessen werden einige der bereits implementierten Use Cases ignoriert, manche werden erweitert und andere werden neu hinzugefügt. Dies ist im Use Case Diagram anhand der Legende ersichtlich.


== Identifizierte Use Cases
// Liste aller identifizierten Use Cases (priorisiert)

* *UC03* (04): Projekt verwalten
* *UC02*: Fragebogen ausfüllen
* *UC06*: Teams generieren
* *UC09*: Backup erstellen/laden
* *UC10*: Gesamtsystem zurücksetzen* 
* *UC05*: Projekt löschen
* *UC07*: Projektteams zurücksetzen
* *UC08*: Teams manuell bearbeiten
* *UC01*: User login


== Use Case Diagramm
// ...

//Fügen Sie nachfolgend alle detaillierten Use-Cases per Include ein.
//Dafür sollten Sie pro Use-Case eine Datei anlegen, die auf dem use_case_01.inc.adoc Template basiert.

////
Mit `<<<` wird im PDF ein Seitenumbruch erzeugt.
Zwischen `include::...` und dem darauf folgenden `<<<` muss sich eine Leerzeile befinden. Fehlt diese, werden unter Umständen die erste Überschriften aus der inkludierten Datei nicht korrekt übernommen.
Ein `include` entfernt am Anfang und Ende eine möglich Leerzeile, was in Kombination mit `<<<` zu Fehlern führen kann.
////

<<<
include::use_case_01.inc.adoc[]

<<<
include::use_case_02.inc.adoc[]

<<<
include::use_case_03.inc.adoc[]

<<<
include::use_case_04.inc.adoc[]

<<<
include::use_case_05.inc.adoc[]

<<<
include::use_case_06.inc.adoc[]

<<<
include::use_case_07.inc.adoc[]

<<<
include::use_case_08.inc.adoc[]

<<<
include::use_case_09.inc.adoc[]

<<<
include::use_case_10.inc.adoc[]
