//Nutzen Sie dieses Template als Grundlage für die Spezifikation *einzelner* Use-Cases. Diese lassen sich dann per Include in das Use-Case Model Dokument einbinden (siehe Beispiel dort).

== Use-Case: UC03 Projekt verwalten

=== Kurzbeschreibung
Der Use Case beschreibt den Prozess der Verwaltung von Projekten durch einen Dozenten.

=== Kurzbeschreibung der Akteure

==== Dozent
Möchte ein oder mehrere Projekte verwalten.

=== Vorbedingungen
//Vorbedingungen müssen erfüllt, damit der Use Case beginnen kann, z.B. Benutzer ist angemeldet, Warenkorb ist nicht leer...

Der Dozent ist mittels seiner HTWD-Logindaten angemeldet und hat sich auf die "Projektübersicht" navigiert.

=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")

. Der Use Case beginnt, wenn der Dozent auf der "Projektübersicht" befindet.
. Der Dozent fügt ein Projekt hinzu oder wählt das zu bearbeitende Projekt aus.
. Das System zeigt den bisherigen oder einen leeren Bearbeitungsstand des (neuen) Projekts an.
. WHILE Projektinformationen sind nicht vollständig
.. In die Felder "Projektname", "Projektbeschreibung" und "Projekt-ID" können per Texteingabe freie Wörter und Sätze eingetragen werden.
.. Das Feld "Projektlabels" zeigt eine Vorauswahl (Weiterentwicklung, Neuentwicklung, usw.) an.
.. Das Feld "Anhang" gibt dem Dozent die Möglichkeit ein PDF-Dokument hochzuladen.
.. Der Dozent nimmt die gewünschten Veränderungen vor und bestätigt seine Eingabe.
.. Der Dozent löst das Speichern des Projektes aus.
.. Das System prüft, ob alle Pflichtfelder entsprechend der Gültigkeitsregeln ausgefüllt wurden.
.. Das System zeigt die neue Version der Projekts an.
.. Das System speichert den neuen Bearbeitungsstand des Projekts in der Datenbank ab.
. Der Use Case ist abgeschlossen.

=== Alternative Abläufe
//Nutzen Sie alternative Abläufe für Fehlerfälle, Ausnahmen und Erweiterungen zum Standardablauf

==== Angabe ungültiger Daten
* (3f) Das System prüft, ob alle Pflichtfelder entsprechend der Gültigkeitsregeln ausgefüllt wurden.
* WHILE Prüfung der Pflichtfelder nicht erfolgreich
... System fordert den Dozent auf, diese zu berichtigen.
... Dozent berichtigt Angaben.
... IF Prüfung erfolgreich
.... Fortsetzung Standardablauf an Schritt (3 g).
... ELSE
.... System verhindert Abspeichern des Projekts.
.... Fortsetzung an Schritt (3 f).

==== Hochladen einer ungültigen Datei
* (3f) Das System prüft, ob alle Pflichtfelder entsprechend der Gültigkeitsregeln ausgefüllt wurden.
... IF Prüfung erfolgreich
.... Fortsetzung Standardablauf an Schritt (3 g).
... ELSE
.... System fordert den Dozenten auf ein PDF-Dokument hochzuladen
.... Fortsetzung an Schritt (3 f).

=== Unterabläufe (subflows)
//Nutzen Sie Unterabläufe, um wiederkehrende Schritte auszulagern

--- nicht vorhanden ---

//==== <Unterablauf 1>
//. <Unterablauf 1, Schritt 1>
//. …
//. <Unterablauf 1, Schritt n>

=== Wesentliche Szenarios
//Szenarios sind konkrete Instanzen eines Use Case, d.h. mit einem konkreten Akteur und einem konkreten Durchlauf der o.g. Flows. Szenarios können als Vorstufe für die Entwicklung von Flows und/oder zu deren Validierung verwendet werden.

==== Bearbeiten des Projekts I8 Teamverwaltung
Der Dozent bearbeitet das Projekt "I8 Teamverwaltung". Er fügt das vorgeschlagene Label "Weiterentwicklung" hinzu. Zusätzlich dazu ändert er die Projektbeschreibung, da hier ein Rechtschreibfehler unterlaufen ist. Er speichert die Änderungen mit dem Klick auf den "Projekt speichern"-Button ab. Nun wird die aktualisierte Version der Projekts I8 Teamverwaltung angezeigt.

=== Nachbedingungen
//Nachbedingungen beschreiben das Ergebnis des Use Case, z.B. einen bestimmten Systemzustand.

Eine neue Version eines (neuen) Projekts ist in der Datenbank hinterlegt.
* Das bearbeitete (neu erstellte) Projekt wird nun aktualisiert angezeigt.

=== Besondere Anforderungen
//Besondere Anforderungen können sich auf nicht-funktionale Anforderungen wie z.B. einzuhaltende Standards, Qualitätsanforderungen oder Anforderungen an die Benutzeroberfläche beziehen.

--- nicht vorhanden ---
