//Nutzen Sie dieses Template als Grundlage für die Spezifikation *einzelner* Use-Cases. Diese lassen sich dann per Include in das Use-Case Model Dokument einbinden (siehe Beispiel dort).

== Use-Case: UC02 Fragebogen bearbeiten und einreichen

=== Kurzbeschreibung
//<Kurze Beschreibung des Use Case>
Der Use Case beschreibt den Abgabeprozess des Fragebogens durch den Studierenden.

=== Kurzbeschreibung der Akteure

==== Studierender
Möchte den Fragebogen ausfüllen und einreichen.

=== Vorbedingungen
//Vorbedingungen müssen erfüllt, damit der Use Case beginnen kann, z.B. Benutzer ist angemeldet, Warenkorb ist nicht leer...

Studierender ist eingeloggt.

=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")

. Der Use Case beginnt, wenn der Studierende nach dem Klick auf den "Anmelden"-Button erfolgreich weitergeleitet wird.
. Das System prüft in der Datenbank ob der Studierende bereits einen Fragebogen ausgefüllt und abgespeichert hat.
. IF gespeicherter Fragebogen gefunden
.. Das System lädt den bisherigen Speicherstand des, dem Studierenden zugeordneten, Fragebogens.
.. Dem Studierender wird der bereits ausgefüllte Fragebogen angezeigt.
. ELSE
.. Dem Studierender wird ein neuer, leerer Fragebogen angezeigt.
. Studierender setzt Häckchen bei den Multiple-Choice-Fragen
. Bei Textfragen wird dem Studierenden ein Textfeld angezeigt, in dem er seine Antwort eingeben kann.
. Der Studierende klickt auf den "Fragebogen speichern"-Button.
. Der Studierende möchte den Fragebogen einreichen.
. Der Studierende klickt auf den "Fragebogen einreichen"-Button.
. Das System fragt den Studierenden mit einem Pop-Up ob er seine Eingaben überprüft hat und wirklich einreichen will.
. Der Studierende bestätigt seine Eingabe mit dem Klick auf den "Ja"-Button.
. Der Use Case ist abgeschlossen.

=== Alternative Abläufe
//Nutzen Sie alternative Abläufe für Fehlerfälle, Ausnahmen und Erweiterungen zum Standardablauf

==== Logout
pass:[#] Studierender bricht den Vorgang durch Schließen des Browsers oder durch Ausloggen ab. Der Use Case ist damit beendet.

==== Leer
(9) Wenn der Studierende den Schritt ausführt, obwohl er nicht alle Felder ausgefüllt hat, gibt das System ein Pop-Up raus, dass den Studierende darüber informiert und so der Fragebogen nicht eingereicht werden kann.

=== Unterabläufe (subflows)
//Nutzen Sie Unterabläufe, um wiederkehrende Schritte auszulagern
==== Speichern
(7) Fragebogen wird auf Änderungen geprüft, wenn der Studierende Änderungen vorgenommen hat, werden diese zu der jeweiligen s-Nummer zugeordnet in der Datenbank gespeichert. 

=== Wesentliche Szenarios
//Szenarios sind konkrete Instanzen eines Use Case, d.h. mit einem konkreten Akteur und einem konkreten Durchlauf der o.g. Flows. Szenarios können als Vorstufe für die Entwicklung von Flows und/oder zu deren Validierung verwendet werden.

==== Erfolgreiches Einreichen des Fragebogens
Studierender X der HTWD füllt alle Felder des Fragebogens ordnungsgemäß aus. Der Studierende trägt außerdem eine bereits absolvierte Ausbildung im Fragebogen an. Der Fragebogen wird erfolgreich eingereicht.

=== Nachbedingungen
//Nachbedingungen beschreiben das Ergebnis des Use Case, z.B. einen bestimmten Systemzustand.
Das System hat den vollständigen Fragebogen gespeichert und wird nun bei der Teamgenerierung beachtet.


=== Besondere Anforderungen
//Besondere Anforderungen können sich auf nicht-funktionale Anforderungen wie z.B. einzuhaltende Standards, Qualitätsanforderungen oder Anforderungen an die Benutzeroberfläche beziehen.
