= Vision: {project-name}
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
Der Zweck dieses Dokuments ist es, die wesentlichen Bedarfe und Funktionalitäten des Online-Tool zur Erstellung und Verwaltung von Gruppen für Software Engineering Projekte zu sammeln, zu analysieren und zu definieren. Der Fokus liegt auf den Fähigkeiten, die von Stakeholdern und adressierten Nutzern benötigt werden, und der Begründung dieser Bedarfe. Die  Details, wie das Online-Tool diese Bedarfe erfüllt, werden in dem <<#use-case_model.adoc, Use-Case Model>> und <<#system-wide_requirement.adoc, System-Wide Requirements>> beschrieben.

=== Zweck
Der Zweck dieses Dokuments ist es, die wesentlichen Anforderungen an das System aus Sicht und mit den Begriffen der künftigen Anwender zu beschreiben.

=== Gültigkeitsbereich (Scope)
Dieses Visions-Dokument bezieht sich auf das Online-Tool zur Erstellung und Verwaltung von Gruppen für Software Engineering Projekte, das von Team I8 entwickelt wird. Das System wird es dem Dozenten erlauben, auf Basis von durch Studierenden ausgefüllten Fragebögen, mit Hilfe eines Algorithmus Teams aus Studierenden generieren zu lassen. Diese Teams sind vorher erstellten Projekten zugeordnet.

=== Definitionen, Akronyme und Abkürzungen
//Verweis passend zum Belegabgabe-Template se1_belegabgabe_t00.adoc
Siehe <<#glossary, Glossar>>.

=== Referenzen
(hier externe Verweise zu anderen Dokumenten, Quellen, Standards etc. einfügen, sofern notwendig)

Möglicherweise Dokumente des Erstellerteams des Tools einfügen.


== Positionierung

=== Fachliche Motivation
//Erläutern Sie kurz den Hintergrund, in dem das Projekt angesiedelt ist. Welches Problem soll gelöst werden, wie ist es entstanden? Welche Verbesserung wird angestrebt. Achten Sie darauf, eine fachliche (organisatorische, betriebswirtschaftliche) Perspektive einzunehmen.

Im Rahmen des Fachs Software Engineering werden interne (innerhalb der HTWD) und externe (Auftraggeber außerhalb der HTWD) Projekte in Teams aus teilnehmenden Studierenden realisiert. Die Studierenden stehen daher vor der Entscheidung an welchem Projekt sie im Semester mitwirken möchten. Um die Präferenzen, Fähigkeiten und Vorerfahrung jedes Studenten in die Teamerstellung einfließen zu lassen, füllen die Studierenden einen Fragebogen, in welchem diese abgefragt werden, aus. Die Teamerstellung bringt einige Probleme mit sich. Einerseits ist die Auswertung der Daten aus dem Fragebogen sehr zeitintensiv. Andererseits nehmen im Modul SE I neben verschiedenen Informatikstudiengängen auch Studierende des Wirtschaftsingenieurwesens teil, wobei die zweit genannten nach dem ersten Semester ausscheiden und im zweiten Semester ausschließlich die Studierenden der Informatik involviert sind. Gegebenfalls werden andere Studierende zum Semesterwechsel zusätzlich an SE II teilnehmen, z.B. aufgrund von Beurlaubung, Wiederholungsprüfung oder Auslandssemester Außerdem müssen folgenede Faktoren beachtet werden:


* Ausgewogene Interessen bzgl. der Rollenverteilung
* Nutzung vorhandener Fähigkeiten, v.a. im technischen Bereich
* Gleichmäßige Verteilung der WING-Studierenden auf die Teams
* Möglichst gleiche Größe der Teams (initial 7-10 Teammitglieder)


Die aktuelle Softwarelösung ist von den Studierenden der letzten beiden Semester erstellt worden, wobei diese im aktuellen Semester erstmals getestet wurde. Jedoch sind hierbei einige Probleme aufgetreten, beziehungsweise Verbesserungswünsche vom Auftraggeber geäußert worden.

=== Problem Statement
//Stellen Sie zusammenfassend das Problem dar, das mit diesem Projekt gelöst werden soll. Das folgende Format kann dazu verwendet werden:

[cols="1,3"]
|===
| Das Problem | [beschreiben Sie das Problem]
| betrifft | [die Stakeholder, die vom Problem betroffen sind]
| die Auswirkung davon ist | [welche Auswirkungen hat das Problem?]
| eine erfolgreiche Lösung wäre | Führen Sie einige wesentliche Vorteile einer erfolgreichen Lösung auf]
|===

////
Beispiel:
[cols="1,3"]
|===
|Das Problem | aktuelle Informationen zum Stundenplan und Noten einfach zu erhalten
|betrifft | Studierende der HTW Dresden
|die Auswirkung davon ist | umständliche und aufwändige Suche nach Noten, Zeiten und Räumen
|eine erfolgreiche Lösung wäre | die Zusammenführung und benutzer-individuelle Darstellung auf einem mobilen Endgerät
|===
////

=== Positionierung des Produkts
//Ein Positionierung des Produkts beschreibt das Einsatzziel der Anwendung und die Bedeutung das Projekts an alle beteiligten Mitarbeiter.

//Geben Sie in knapper Form übersichtsartig die Positionierung der angestrebten Lösung im Vergleich zu verfügbaren Alternativen dar. Das folgende Format kann dazu verwendet werden:

[cols="1,3"]
|===
| Für | [Zielkunde / Nutzer]
| der / die | [Angabe des Bedarfs oder Chance]
| Das Produkt / die Lösung ist ein | [Produktkategorie]
| Die / Das | [Aussage zum Hauptvorteil / Alleinstellungsmerkmal]
| Im Gegensatz zu | [wesentliche Lösungsalternative]
| Unser Produkt | [Aussage zum Hauptunterschied]
|===

////
Beispiel Produkt:
|===
| Für | Studierende der HTW
| die | die ihren Studienalltag effizienter organisieren möchten
| Das Produkt ist eine | mobile App für Smartphones
| Die | für den Nutzer Informationen zum Stundenplan und Noten darstellt
| Im Gegensatz zu | Stundenplänen der Website und HIS-Noteneinsicht
| Unser Produkt | zeigt nur die für den Nutzer relevanten Informationen komfortabel auf dem Smartphone an.
|===
////


== Stakeholder Beschreibungen


[%header, cols="1,3,3"]
|===
| Name | Beschreibung | Verantwortlichkeiten

| Projektteam I8
| Berarbeiter des Projektes I8
| Überarbeiten des bestehenden Bewerbungsprozesses für die Projektarbeit im Modul SE1
| Studierende 
| Kursteilnehmer im Modul SE1,
*Wirtschaftsinformatiker 
*Wirtschftsingenieure
*Informaiker
*Verwaltungsinformatiker
| Endnutzer des Produktes
| Auftraggeber
| Herr Zirkelbach
| 
* Endnutzer des Produktes
* ist für die Verwaltung zuständig
* Ansprechpartner und Festleger der Anforderungen 
| Rechenzentrum der HTW
| betreibt zentrale Server und Dienste der HTW
| stellt Zertifikat bereit
| 
|===

=== Benutzerumgebung


//Zutreffendes angeben, nicht zutreffendes streichen oder auskommentieren

==== Für Dozent

. Die Anzahl Dozenten, ist abhängig davon wie viele Dozenten dieses Projekt bearbeiten. Dies sollte sich in der Regel nicht ändern. 

. Die Bearbeitungsdauer der Aufgabe ist abhängig von der Aufgabe, die in Anspruch genommen wird.

. Eine mobile Version des bestehenden Programmes ist wünschenswert



==== Für Admin

. Die Anhzahl der Teilnehmer ist abhängig von der Anzahl der Studierenden, die das Projekt in SE1 in Angriff nehmen

. Die Aufgabe sollte in etwa 20 Minuten in Anspruch nehmen

. Die Bewerbung kann nur online erfolgen

. Eine mobile Anwendung soll gewährleistet werden

//. Wie lange dauert die Bearbeitung der Aufgabe? Wie viel Zeit wird für jeden Arbeitsschritt benötigt? Ändert sich das?
//. Gibt es besondere Umgebungsbedingungen, z.B. mobil, offline, Außeneinsatz, Touchbedienung, Nutzung durch seh- oder hörbeeinträchtigte Personen?
//. Welche Systemplattformen werden heute eingesetzt? Welche sind es ggf. zukünftig?
//. Welche anderen Anwendungen sind im Einsatz? Muss ihre Anwendung mit diesen integriert werden?

//Hier können zudem bei Bedarf Teile des Unternehmensmodells (Prozesse, Organigramme, IT-Landschaft, ...) eingefügt werden, um die beteiligten Aufgaben und Rollen zu skizzieren.


== Produkt-/Lösungsüberblick

=== Bedarfe und Hauptfunktionen
//Vermeiden Sie Angaben zum Entwurf. Nennen wesentliche Features (Produktmerkmale) auf allgemeiner Ebene. Fokussieren Sie sich auf die benötigten Fähigkeiten des Systems und warum (nicht wie!) diese realisiert werden sollen. Geben Sie die von den Stakeholdern vorgegebenen Prioritäten und das geplante Release für die Veröffentlichung der Features an.

[%header, cols="4,1,4,1"]
|===
| Bedarf | Priorität | Features | Geplantes Release
| xx | xx | xx | xx
|===


== Zusätzliche Produktanforderungen
//Zutreffendes angeben, nicht zutreffendes streichen oder auskommentieren
Hinweise:

. Führen Sie die wesentlichen anzuwendenden Standards, Hardware oder andere Plattformanforderungen, Leistungsanforderungen und Umgebungsanforderungen auf
. Definieren Sie grob die Qualitätsanforderungen für Leistung, Robustheit, Ausfalltoleranz, Benutzbarkeit und ähnliche Merkmale, die nicht von den genannten Features erfasst werden.
. Notieren Sie alle Entwurfseinschränkungen, externe Einschränkungen, Annahmen oder andere Abhängigkeiten, die wenn Sie geändert werden, das Visions-Dokument beeinflussen. Ein Beispiel wäre die Annahme, dass ein bestimmtes Betriebssystem für die vom System erforderliche Hardware verfügbar ist. Ist das Betriebssystem nicht verfügbar, muss das Visions-Dokument angepasst werden.
. Definieren Sie alle Dokumentationsanforderugen, inkl. Benutzerhandbücher, Onlinehilfe, Installations-, Kennzeichnungs- und Auslieferungsanforderungen-
. Definieren Sie die Priorität für diese zusätzlichen Produktanforderungen. Ergänzen Sie, falls sinnvoll, Angaben zu Stabilität, Nutzen, Aufwand und Risiko für diese Anforderungen.

[%header, cols="4,1,1"]
|===
| Anforderung | Priorität | Geplantes Release
| xx | xx | xx
|===
