= Architecture Notebook: \{project-name}
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
\{localdatetime}
include::../_includes/default-attributes.inc.adoc[] 
// Platzhalter für weitere Dokumenten-Attribute


== Zweck
Dieses Dokument beschreibt die Philosophie, Entscheidungen, Nebenbedingungen, Begründungen, wesentliche Elemente und andere übergreifende Aspekte des Systems, die Einfluss auf Entwurf und Implementierung haben. Die für die Architektur getroffenen Entscheidungen und Ihre Hintergründe werden hier festgehalten.

//Hinweise: Bearbeiten Sie immer die Abschnitte 2-6 dieser Vorlage. Nachfolgende Abschnitte sind empfohlen, aber optional und sollten je nach Umfang der künftigen Wartungsarbeiten, Fähigkeiten des Entwicklungsteams und Bedeutung anderer architektureller Belange.

//Anmerkung: Die Architektur legt wesentliche EINSCHRÄNKUNGEN für den Systementwurf fest und ist ein Schlüssel für die Erfüllung nicht-funktionaler Eigenschaften!

== Architekturziele und Philosophie
//Hinweise: Beschreiben Sie die Philosophie der Architektur, d.h. den zentralen Ansatz für ihre Architektur. Identifizieren Sie alle Aspekte, die die Philosophie beeinflussen, z.B. komplexe Auslieferung Aspekte, Anpassung von Altsystemen oder besondere Geschwindigkeitsanforderungen. Muss es besonders robust sein, um eine langfristige Wartung und Pflege zu ermöglichen?

//Formulieren Sie eine Reihe von Zielen, die die Architektur in ihrer Struktur und ihrem Verhalten erfüllen muss. Identifizieren Sie kritische Fragen, die von der Architektur adressiert werden müssen, z.B. besondere Hardware-Abhängigkeiten, die vom Rest des Systems isoliert werden sollten oder Sicherstellung der Funktionsfähigkeit unter besonderen Bedingungen (z.B. Offline-Nutzung).

Die Architektur muss eine Webanwendung für Studenten und Professoren, welche es ermöglicht Teams mit der gleichen Anzahl der Studenten jedoch unterschiedlicher Rollen in verschiedenen Projekten aufzuteilen, verwirklichen. Diese basiert auf einer bereits bestehenden Anwendung und
ist somit als Weiterentwicklung zu betrachten. Unsere Schwerpunkte bei der Architektur der Weiterentwicklung liegen auf der Nutzerfreundlichkeit für Studenten, sowie Projektadministrator und der Erweiterung des bereits vorhandenen Algorithmus.

Weitere Ziele, die die Architektur in Bezug auf Struktur und Verhalten
erreichen soll, sind:

* Es muss die Möglichkeit bestehen, das Programm über mehrere Semester
zu verwenden.

* Das Zurücksetzen und Neuerstellen der Website 

* Das Einbinden neuer Projekte

* Das Erstellen von Gruppen unterschiedlicher Größe, sowie Anzahl an Projekten

== Annahmen und Abhängigkeiten

//[List the assumptions and dependencies that drive architectural decisions. This could include sensitive or critical areas, dependencies on legacy interfaces, the skill and experience of the team, the availability of important resources, and so forth]

Grundannahme:

* Die Weiterentwicklung eines bestehenden Systems

* Ein System zur Erstellung und Verwaltung von Gruppen in Software
Engineering Projekten und des Fragebogens der Studenten.

* Python ist als Programmiersprache für das Backend zu verwenden.

* Das Framework für das Backend ist Django.

* Die Software wird über eine virtuelle Maschine, Docker Container, betrieben.

* Die virtuelle Maschine läuft über Linux.

* Als Datenbank wird MySQL verwendet.

* Die Anmeldung erfolgt über den HTW-Login.

* Für das Frontend wird als Programmiersprache JavaScript verwendet.

* Zur Oberflächengestaltung werden HTML und CSS verwendet.

== Architektur-relevante Anforderungen

//Fügen Sie eine Referenz / Link zu den Anforderungen ein, die implementiert werden müssen, um die Architektur zu erzeugen.

*Functional*

* Speicherplatz um verschiedene Versionen der Website zu speichern, dieser muss für Dozenten zugänglich sein.

*SWFA-1*

* Um das Speichern von inkonsistenten Daten zu verhindern soll bei dem Speichervorgang eine Überprüfung der eingegebenen Daten stattfinden. Auch
mögliche Pflichtfelder müssen berücksichtigt werden.

*SWFA-4*

* Um faire Teams erstellen zu können, soll der Dozent die Möglichkeit haben, durch ein Eingabefeld festzulegen wie viele Personen in ein Team mindestens sein müssen. Hierfür muss der Algorithmus mit einer variablen Anzahl an Teams arbeiten können. 

*SWFA-5*

* NFAF-1 Das System muss den Fragebogen der Studenten, die Accountdaten, sowie die Projektdaten des Professors speichern.

* NFAF-2 Das System muss sicherstellen, dass die Anwendung nur im Netzwerk der HTW Dresden funktioniert.

* Die Nutzbarkeit muss gewährleistet sein, für den unwahrscheinlichen Fall, dass 20 Nutzer gleichzeitig die Webseite nutzen.

* Die Performance unserer Seite kann mittels einem Hosting über die HTW, als auch mit der Verminderung unnötigem Traffics gewährleistet werden.

*NFAP-1*, *NFAR-1*

* Ausreichende Dokumentierung, um das Veröffentlichen/ Schließen der Webseite durch Dozenten zu garantieren.

* Hierfür wird bei dem Beenden der Website eine Meldung auftauchen, ob man die Seite wirklich verlassen möchte, wodurch möglicherweise nicht gespeicherte Daten verloren gehen.

*NFAS-1:*

== Entscheidungen, Nebenbedingungen und Begründungen

//[List the decisions that have been made regarding architectural approaches and the constraints being placed on the way that the developers build the system. These will serve as guidelines for defining architecturally significant parts of the system. Justify each decision or constraint so that developers understand the importance of building the system according to the context created by those decisions and constraints. This may include a list of DOs and DON’Ts to guide the developers in building the system.]

. Aufbauend auf der bereits verwendeten Website haben wir uns entschieden folgende Punkte zu übernehmen:

.. Datenbanken basierend auf MySQl

.. Programmiersprache Python, Java Script und CSS .. Bibliotheken und Framework von Django

.. Konfiguration über Docker

. Als Schnittstelle der Website verwenden wir ngnix, da auch diese bereits von der bestehenden Website benutzt wurde.

== Architekturmechanismen

// https://www2.htw-dresden.de/~anke/openup/core.tech.common.extend_supp/guidances/concepts/arch_mechanism_2932DFB6.html[Doku "Concept: Architectural Mechanism"] //[List the architectural mechanisms and describe the current state of each one. Initially, each mechanism may be only name and a brief description. They will evolve until the mechanism is a collaboration or pattern that can be directly applied to some aspect of the design.]

//Beispiele: relationales DBMS, Messaging-Dienste, Transaktionsserver, Webserver, Publish-Subscribe Mechanismus

//Beschreiben Sie den Zweck, Eigenschaften und Funktion der Architekturmechanismen.

. System Management - Erreichbarkeit

Da die Website bereits für Linux erstellt wurde, haben wir uns dazu entschieden dies zu übernehmen, sodass die Website auch in Zukunft im HTW-Netzwerk über Linux laufen wird.

Abrufbar ist die Website jedoch von jedem Browser auf jedem Betriebssystem, während man sich in dem HTW-Netzwerk befindet.

. Security - Zugangsberechtigung

Zugang zum Fragebogen sollen nur jene Studenten haben, welche sich in OPAL für den Beleg eingeschrieben haben. Dafür haben wir einen Login im HTW-Account, welcher nur im HTW-Netzwerk funktioniert.

Das Ausfüllen des Fragebogens außerhalb der HTW ist mittels eines VPN möglich.

. Communication - Problem adaption

Wenn es zu der Situation kommen sollte das es in einem Semester zu wenig oder zu viele Projektthemen geben sollte, hat der Dozent die Möglichkeit die Anzahl der Teammitglieder festzulegen.

Daraufhin soll der Algorithmus eine Konstellation erstellen bei der die meist gefragtesten Themen priorisiert oder doppelt verwendet werden sollen.

Diese einzelnen Szenarien müssen in dem Algorithmus beachtet werden.

. Archiving - Sicherheitsabfrage

Wenn man die Website verlässt oder zu einem Unterpunkt der Website navigiert, wird der Benutzer der Dozentenansicht gefragt, ob die ausgefüllten Daten gespeichert werden sollen.

. Memory Management - Wiederherstellung der Webseite

Es soll es die Möglichkeit geben über einen Speicher eine bestimmte Version von einem ausgewählten Zeitpunkt wieder herzustellen, im Falle von Komplikationen oder Fehlern auf der Webseite.

== Wesentliche Abstraktionen


. Teamstabelle

Darstellung der fertig generierten Teams und deren Thema. Diese wird vom Dozenten betrachtet. Es zeigt die Teams mit ihren Projektleiter.

. Projekttabelle

Zeigt die Projekte mit der wesentlichen Beschreibung und deren Ansprechpartner. Sortiert sind die Projekte nach ihrer ID welche vom Dozenten manuell vergeben wird. Abgebildet wird sie für den Dozent, aber auch oberhalb des Fragebogens ist sie für die Studenten einsehbar.

. Nutzer .. Dozent:

In der Rolle des Admins welcher auf der Dozentenwebsite die Projekte
anlegt, Teams generiert und im Zweifel die Teams manuell bearbeitet.

.. Student:

In der Rolle des Besuchers. Von ihm werden auf der Studentwebsite
Antworten verlangt die später bei der Teamerstellung verwendet werden.

== Schichten oder Architektur-Framework

Model-View-Controller(MVC)

Im Model arbeiten wir mit Docker ein Open-Source Tool welches uns eine
portable und konsistente Laufzeitumgebung für unsere Software bietet,
zudem arbeiten wir auch noch mit dem Webframework Django.

In der View arbeiten wir mit HTML und CSS, mittelfristig wollen wir
dafür auch ein Template benutzen.

Zuletzt zum Controller dort verwenden wir OpenSSH für einen sicheren
Zugriff auf das Netzwerk. Außerdem benutzen wir nginx als Webserver.

== Architektursichten (Views)

=== Logische Sicht

Unser System, welches für eine Nutzung im HTW Netzwerk vorgesehen ist, 
besteht weitestgehend aus internen Verbindung. Wie im unten anliegenden 
C4 Model zu sehen ist die einzige Schnittstelle nach außen, die 
Verbindung zu dem LDAP Server der HTW Dresden. Jener gibt uns die Möglichkeit,
die Authentifizierung für unser Website über den bereits bestehenden HTW Login
zu gestalten. Diese Entscheidung ist auch wieder mit der Nutzer Freundlichkeit
aber auch der Sicherheit zu begründen, einerseits muss keine externe Seite 
verwendet werden und zum anderen muss kein neuer Login angelegt werden. 
Dies lässt den Nutzer die Website sofort verwenden ohne auf eine 
Bestätigungsemail oder ähnliches zu warten. 

=== Physische Sicht (Betriebssicht)

//Beschreibt die physischen Knoten (Rechner) des Systems, der Prozesse,
Threads und Komponenten, die in diesen Knoten ausgeführt werden. Diese
Sicht wird nicht benötigt, wenn das System in einem einzelnen Prozess
oder Thread ausgeführt wird.

=== Use cases

//Eine Liste oder ein Diagramm der Use Cases, die architektur-relevante
Anforderungne enthalten.
