= Iteration Plan 05: {project-name}
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Meilensteine
//Meilensteine zeigen den Ablauf der Iteration, wie z.B. den Beginn und das Ende, Zwischen-Meilensteine, Synchronisation mit anderen Teams, Demos usw.

[%header, cols="3,1"]
|===
| Meilenstein | Datum

| Beginn der Iteration | 16.01.23
| Meeting mit Auftraggeber/ Coach | 18.01.23
| Zwischenmeeting| 21.01.23
| Ende der Iteration | 27.01.23
|===


== Wesentliche Ziele

. Glossar fertiggestellen
. Domänenmodell fertigstellen
. Use Case Model vervollständigen
. Zu präsentierende Dokumente für den Beleg auswählen
. Projektplan fertigstellen
. Architecture Notebook fertigstellen
. Test Cases ausarbeiten
. Belegabgabe auf Vollständigkeit, Sinnhaftigkeit und Rechtschreibung prüfen


== Aufgabenzuordnung
//Dieser Abschnitt sollte einen Verweis auf die Work Items List enthalten, die die für diese Iteration vorgesehenen Aufgaben dokumentiert sowie die Zuordnung dieser Aufgaben zu Teammitgliedern. Alternativ können die Aufgaben für die Iteration und die Zuordnung zu Teammitgliedern in nachfolgender Tabelle dokumentiert werden - je nach dem, was einfacher für die Projektbeteiligten einfacher zu finden ist.

Die in dieser Iteration geplanten/ fertiggestellten Aufgaben sind als Issues in unserem https://github.com/users/Norinofa/projects/1/views/13[GitHub Project] dargestellt.

Bild einfügen

== Probleme
//Optional: Führen Sie alle Probleme auf, die in dieser Iteration adressiert werden sollen. Aktualisieren Sie den Status, wenn neue Probleme bei den täglichen / regelmäßigen Abstimmungen berichtet werden.

[%header, cols="2,1,3a"]
|===
| Problem | Status | Notizen

| Einbindung des Glossars in gesamte Projektlaufzeit
| rot
| 
* Das Team hat das Glossar während des Projektes vernachlässigt, was jetzt einen intensiven Zeitaufwand beansprucht.
* Dies betrifft alle Mitglieder des Teams. 
* Das Glossar ist von den Hauptverantwortlichen der einzelenen Dokumente bis zum 26.01.23 zu ergänzen.
| Architecture Notebook wurde nicht überprüft
| rot
| 
* Das Architecture Notebook weist Lücken und Formatierungsprobleme auf.
* Dies behindert die Überprüfung der Datei lediglich auf Rechtschreibung und Grammatik.
* Es muss dringend auf Inhalt und Logik geprüft und überarbeitet werden. Diese Aufgabe wird den Architekten zugeteilt und muss bis zum 26.01.23 fertiggestellt werden, um eine Korrekturlesung zu gewährleisten.

|===


== Bewertungskriterien
//Eine kurze Beschreibung, wie Erfüllung die o.g. Ziele bewertet werden sollen.

* Das Use Case Model wurde vom Auftraggeber als sinnvoll erachtet.
* Alle abzugebenen Dokumente sind vollständig, sinnvoll und grammatikalisch, sowie von der Rechtschreibung korrekt.
* Die gewählten Test Cases sind ausgearbeitet und mit einer Visualisierung hinterlegt.
* Es wurden 2 Iterationspläne zur Abgabe gewählt und zur Abgabe vorbereitet.

== Assessment
//In diesem Abschnitt werden die Ergebnisse und Maßnahmen der Bewertung erfasst und kommuniziert. Die Bewertung wird üblicherweise am Ende jeder Iteration durchgeführt. Wenn Sie diese Bewertungen nicht machen, ist das Team möglicherweise nicht in der Lage, die eigene Arbeitsweise ("Way of Working") zu verbessern.

[%header, cols="1,3"]
|===
| Assessment Ziel | Das kann die gesamte Iteration oder eine spezifische Komponente sein

| Assessment Datum | 24.01.2023
| Teilnehmer | Evelyn Dietrich, Kilian Schinnerling
| Projektstatus	| gelb
|===

*Beurteilung im Vergleich zu den Zielen*
//Dokumentieren Sie, ob die angestrebten Ziele des Iterationsplans erreicht wurden.

* _Ziel 1_ wurde erreicht.
* _Ziel 2_ wurde erreicht.
* _Ziel 3_ wurde erreicht. Der Auftraggeber hat das Use Case Model für den derzeitigen Stand als richtig erachtet, jedoch angemerkt, dass das sich die Prisosierung der Use Cases im Verlauf des Projektes ändern kann.
* _Ziel 4_ wurde erreicht. Die Iterationspläne beinhalten alle wesentlichen Aspekte, die in der Iterationsphase vorgefallen sind.
* _Ziel 5_ wurde erreicht. Der Projektplan spiegelt die genaue Arbeitsweise des Teams wieder und wurde auf auf Vollständigkeit und Richtigkeit geprüft. 
* _Ziel 6_ wurde größtenteils erreicht.
* _Ziel 7_ wurde erreicht.
* _Ziel 8_ wurde größtenteils erreicht. Aus unserer Sicht wurden die Dokumente als vollständig, sinnvoll und grammatikalisch sowie von der Rechtschreibung als richtig angesehen. Trotzdessen bestehen Zweifel am Architecture Note, wie bereits angemerkt.

*Beurteilung im Vergleich zu den Bewertungskriterien*
//Document whether you met the evaluation criteria as specified in the Iteration Plan.
//Geben Sie an, ob Sie die o.g. Bewertungskriterien erfüllt haben. Das kann z.B. folgende Informationen enthalten: “Demo for Department X was well-received, with some concerns raised around usability,” or “495 test cases were automated with a 98% pass rate. 9 test cases were deferred because the corresponding Work Items were postponed.”

* _Ziel 3:_ Der Auftraggeber hat das Use Case Model für den derzeitigen Stand als richtig erachtet, jedoch angemerkt, dass das sich die Prisosierung der Use Cases im Verlauf des Projektes ändern kann.
* _Ziel 6:_ Durch die verspätete Kontrollierung auf Sinnhaftigkeit und wenig Kommunikation mit dem Auftraggeber unsererseits, besteht die Chance auf mangelnde Kenntnisse und demzufolge fehlerhafte Vervollständigung des Architecture Notebooks.
* _Ziel 7:_  Die Test Cases wurden zusätzlich mit einer visualisierten Darstellung hinterlegt, die nur zu Veranschaulichung dienen soll, jedoch noch keinen Endzustand darstellt. Der Caoch hat diese spontan am 26.01.23 überprüft und die Darstellung akzeptiert, als auch Verbesserungen vorgeschlage, die im Nachhinein brücksichtigt wurden.


//* Geplante vs. erledigte Aufgaben*
//Zusammenfassung, ob alle für die Iteration geplanten Aufgaben bearbeitet wurden und welche Aufgaben verschoben oder hinzugefügt wurden.


*Andere Belange und Abweichungen*
//Führen Sie weitere Themen auf, für die eine Bewertung durchgeführt wurde. Beispiele sind Finanzen, Zeitabweichungen oder Feedback von Stakeholdern, die nicht bereits an anderer Stelle dokumentiert wurden.
* Bewertung der Arbeitsweise: Auf das gesamte Projekt bezogen wurde an einigen Stellen lückenhaft gearbeitet, sodass extreme Zeitabweichungen bei der Korrektur der Belegarbeit entstanden sind. Letzte Fragen konnten kurzfristig mit dem Coach abgeklärt werden. Dies ist keine dauerhafte Arbeitsweise und muss in den nächsten Iteration Verbesserungen aufzeigen. Dafür muss jedes Teammitglied den OpenUP nochmal verinnerlichen und bei Fragen rechtzeitig den Coach, Auftraggeber oder externe Hilfe um Antworten bitten. 
