= Projektplan: {project-name}
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
//Briefly describe the content of the project plan.

In diesem Projektplan der Gruppe "I8 Erstellung und Verwaltung von Gruppen für Software Engineering Projekte" wird die Vorgehensweise und Organisation des Projektes protokolliert. Anhand des Open Unified Process wird das Projekt durch mehrere Iterationsschritte organisiert um bestmögliche Ergebnisse zu erzielen. Während des gesamten Projektes wird dieses Dokument stetig überarbeitet und der Erkenntnisse des Teams angepasst.


== Projektorganisation
//Introduce the project team, team members, and roles that they play during this project. If applicable, introduce work areas, domains, or technical work packages that are assigned to team members. Introduce neighboring projects, relationships, and communication channels. If the project is introduced somewhere else, reference that location with a link.
In der folgenden Tabelle werden die Teammitglieder und deren Rollenverteilung dargestellt. Die Aufgaben wurden zum Teil doppelt verteilt. Die Rolle, die zuerst benannt wird, weist darauf hin, dass die Person die Hauptverantwortung in dieser Position trägt. Jedoch haben wir uns als Team darauf geeinigt, jeden Bereich zu unterstützen. 

[%header, cols="1,1,1,1"]

|===
| Name | Rolle | Studiengang | Informationen zur Person 
| Evelyn Dietrich 
| Teamleiterin, Testerin 
| Wirtschaftsinformatik 
|
* SHK an der HTW Dresden
* optimistisch
| Kilian Luca Schinnerling 
| Analyst, Teamleiter 
| Wirtschaftsingenieurwesen 
|
| Hieu Trung Thi 
| Analyst 
| Wirtschaftsinformatik 
|
| Phil Benedikt Beck 
| Entwurf 
| Wirtschaftsinformatik 
|
| Julius Wyrembek 
| Tester, Entwurf 
| Wirtschaftsinformatik 
|
| Viktoria Karklin 
| Implementiererin 
| Informatik 
|
*Effiziente Studentin
| Nuha Alhamiidi 
| Implementiererin 
| Wirtschaftsinformatik 
|                                     
|===



== Praktiken und Bewertung
//Describe or reference which management and technical practices will be used in the project, such as iterative development, continuous integration, independent testing and list any changes or particular configuration to the project. Specify how you will track progress in each practice. As an example, for iterative development the team may decide to use iteration assessments and iteration burndown reports and collect metrics such as velocity (completed work item points/ iteration).

Das Team orientiert sich durchgehend am dem Open Unified Process (OpenUP). OpenUP ist ein agiler, vollständiger Softwareentwicklungsprozess zum Erstellen eines Systems. Der OpenUP enthält vorgegebene Rollen, die wir von Anfang an, anhand von Stärken und Schwächen, aufgeteilt haben. Durch die zyklische Arbeitsweise, werden in jeder Iteration unterschiedliche Mirkoinkremente durch jedes einzelne Teammitglied erarbeitet, die dann im Laufe der nächsten Iteration aufeinander aufbauen und ein Gesamtbild erkennen lassen.

Das komplette Projekt wird in Iterationsphasen eingeteilt. Dafür wird ein Treffen aller 2 Wochen festgelegt, entweder persönlich oder online. Die wesentlichen Inhalte dieser Meetings sind: Haben wir unsere Iterationsziele geschafft? Falls nicht, was muss noch erledigt werden und bis wann? Welche Aufgaben müssen während der nächsten Iterationsphase erledigt werden? 
Die Aufgaben für die nächste Iteration werden nach den Meetings in den Projects als Issues https://github.com/users/Norinofa/projects/1[GitHub Project] hinzugefügt, die von jedem Mitglied selbstständig aktualisiert werden. Weiterhin findet man die zugewiesenen Aufgaben in dem jeweiligen Iterationsplan. Nach Ende der Iterationsphase werden die nicht erledigten Ziele in die neue Iterationsphase eingebunden.
Anfangs wurde die gesamte Organisation über eine selbstgeschriebene Work-Items-List gemanagt. Jedoch hat sich diese als unpraktisch erwiesen, da die Teammitglieder ihre Arbeitschritte dort nicht vermerkt haben und generell kein analysierter Fortschritt zu erkennen war.
In Projects hingegen wird die ganze Organisation verwaltet. Dort haben wir Einsicht über neue Aufgaben, noch zuerledigende Aufgaben und den Prozessfortschritt, was die Organisation effektiver und übersichtlicher macht. 


Unsere Kommunikation verläuft größtenteils über Discord. Dort können mehrere Chats themenorientiert eröffnen werden und dies bietet eine bessere Übersicht für die Teammitglieder über die zu erledigenden Anfoderungen. Jedoch nutzen wir für kurze Fragen und schnelle Antworten Whatsapp.

//Hier Bild einfügen des Discords

Weiterhin halten wir unsere Gruppenmeetings meist online ab, da sich durch längere Fahrzeiten und unterschiedliche Stundenpläne Terminfindung für Präsenzmeetings als schwierig erwiesen haben. Für die Onlinetreffen eignen sich die Sprachchats bei Discord. Die Bearbeitung der Dokumente wird überwiegend in Gruppen über Discord in den verschiedenen Sprachchats erledigt, weil man bequem seinen Bildschirm teilen kann und mehrere Meinungen abgedeckt werden können, um das bestmögliche Ergebnis zu erzielen.

== Meilensteine und Ziele
//Define and describe the high-level objectives for the iterations and define milestones. For example, use the following table to lay out the schedule. If needed you may group the iterations into phases and use a separate table for each phase

[%header, cols="1,3a,2,1"]
|===
| Iteration
| Primary objectives +
(risks and use case scenarios)
| Scheduled start or milestone
| Target velocity

| I1
|
* Kennenlernen der Gruppe 
* Rollen verteilen/ mit Aufgaben vertraut machen
* Repo Url senden
* Meeting mit Auftraggeber/ Coach wahrnehmen
* Kommunikationweg finden
| 17.11.22-28.11.22
| 11

| I2
|
* Use Cases ausarbeiten
* Vision schreiben
* Projektplan anfangen
* in vorherrschenden Code einarbeiten/ Docker verstehen
| 28.11.22-16.12.22
| 19

| I3
|
* Use Case Model/Diagramm anpassen
* Architecture Notebook aktualisieren
| 16.12.22-03.01.23
|18

| I4
|
* Prototypvorstellung
* Glossar, Domänenmodel ausarbeiten
* Architecure Notebook vervollständigen
| 03.01.23-16.01.23
|13
| I5
|
* alle Dokumente beenden
* alle Dokumente auf Sinnhaftigkeit, Vollständigkeit und Rechtschreibung prüfen
|16.01.23-27.01.23
|11
|===


== Deployment
//Outline the strategy for deploying the software (and its updates) into the production environment.


== Erkenntnisse (Lessons learned)
//List lessons learned from the retrospective, with special emphasis on actions to be taken to improve, for example: the development environment, the process, or team collaboration.

* Kommunikation zwischen den Mitgliedern und ständigen Kontakt zu den Steakholdern erleichtert die Arbeit
* wenn man einzelne Aufgaben in Gruppen bearbeitet, wird das Ergebnis qualitativ wertvoller
* wenn man die Stärken und Schwächen der Teammitglieder von vornherein kennt, dann klappt die Verteilung der Aufgaben besser
* besser zu viel als zu wenig fragen, egal ob es die Gruppe, den Couch oder den Auftraggeber betrifft
* die Bearbeitung des Projektes direkt nach Erhalt der Aufgabenstellung anzufangen, war eine gute Entscheidung. Man konnte so dem zeitlichen Druck kurz vor der Abgabe entgehen und hatte noch genug Puffer um die Dokumente auf Sinnhaftigkeit, Vollständigkeit und Rechtschreibung zu überprüfen.

