= Projektplan: I8 Erstellung und Verwaltung von Gruppen
für Software Engineering Projekte

Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
//Briefly describe the content of the project plan.

In diesem Projektplan der Gruppe I8 wird die Vorgehensweise und Organisation des Projektes protokolliert. Anhand des Open Unified Process wird das Projekt durch mehrere Iterationsschritte organisiert um bestmögliche Ergebnisse zu erzielen. Während des gesamten Projektes wird dieses Dokument stetig überarbeitet und der Erkenntnisse des Teams angepasst.


== Projektorganisation
//Introduce the project team, team members, and roles that they play during this project. If applicable, introduce work areas, domains, or technical work packages that are assigned to team members. Introduce neighboring projects, relationships, and communication channels. If the project is introduced somewhere else, reference that location with a link.
In der folgenden Tabelle werden die Teammitglieder und deren Rollenverteilung dargestellt. Die Aufgaben wurden zum Teil doppelt verteilt. Die Rolle, die zuerst benannt wird, weist darauf hin, dass die Person die Hauptverantwortung in dieser Position trägt. Jedoch haben wir uns als Team darauf geeinigt, jeden Bereich zu unterstützen. 

[%header, cols="1,1,1"]

|===
| Name | Rolle | Studiengang
| Evelyn Dietrich | Teamleiterin, Testerin | Wirtschaftsinformatik
| Kilian Luca Schinnerling | Analyst, Teamleiter | Wirtschaftsingenieur 
| Hieu Trung Thi | Analyst | Wirtschaftsinformatik
| Phil Benedikt Beck | Entwurf | Wirtschaftsinformatik 
| Julius Wyrembek | Tester, Entwurf | Wirtschaftsinformatik
| Viktoria Karklin | Implementiererin | Informatik
| Nuha Alhamiidi | Implementiererin | Wirtschaftsinformatik                                       
|===



== Praktiken und Bewertung
//Describe or reference which management and technical practices will be used in the project, such as iterative development, continuous integration, independent testing and list any changes or particular configuration to the project. Specify how you will track progress in each practice. As an example, for iterative development the team may decide to use iteration assessments and iteration burndown reports and collect metrics such as velocity (completed work item points/ iteration).

*Scrum Board einrichten?*

Das komplette Projekt wird über Iterationsphasen erstellt. Dafür treffen wir uns aller 2 Wochen entweder persönlich oder online zu einem Meeting. Die wesentlichen Inhalte dieser Meetings sind: Haben wir unsere Iterationsziele geschafft? Falls nicht, was muss noch erledigt werden und bis wann? Welche Aufgaben müssen während der nächsten Iterationsphase erledigt werden? Diese Erkenntnisse werden protokolliert und in gesonderten Protokollen festgehalten. Die Aufgaben für die nächste Iteration werden nach den Meetings in der (Verweis Workitemslist) notiert, die von jedem Mitglied selbstständig aktualisiert wird. 

Die Bearbeitung des Projektes beinhaltet vorgefertigte Dokumente, die mittels GitHub erstellt werden. ( Über die genutzte Funktion Issues werden ...)

Unsere Kommunikation verläuft ausschließlich über Discord, da dort mehrere Chats themenorientiert eröffnen werden können und dies eine bessere Übersicht für die Teammitglieder über die jeweils zu erledigenden Anfoderungen bietet, im gegensatz zu unserem anfänglichen Tool Whatsapp. Weiterhin nutzen wir die Sprachchats um eine effektivere und schnellere Bearbeitung der Schwierigkeiten generieren zu können.



== Meilensteine und Ziele
//Define and describe the high-level objectives for the iterations and define milestones. For example, use the following table to lay out the schedule. If needed you may group the iterations into phases and use a separate table for each phase

[%header, cols="1,3a,2,1"]
|===
| Iteration
| Primary objectives +
(risks and use case scenarios)
| Scheduled start or milestone
| Target velocity

| I1
|
* Kennenlernen der Gruppe 
* Rollen verteilen/ mit Aufgaben vertraut machen
* Repo Url senden
* Meeting mit Auftraggeber/ Coach wahrnehmen
* Kommunikationweg finden
| 17.11.22-28.11.22
| 11

| I2
|
* Use Cases ausarbeiten
* Vision schreiben
* Projektplan anfangen
* in vorherrschenden Code einarbeiten/ Docker verstehen
| 28.11.22-16.12.22
| 19
|===


== Deployment
//Outline the strategy for deploying the software (and its updates) into the production environment.


== Erkenntnisse (Lessons learned)
//List lessons learned from the retrospective, with special emphasis on actions to be taken to improve, for example: the development environment, the process, or team collaboration.

*Kommunikation zwischen den Mitgliedern und ständigen Kontakt zu den Steakholdern erleichtert die Arbeit
