version: "3.9"
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: studentdb
      MYSQL_USER: Nuha
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql
  web:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
  spring:
    image: openjdk:20-jdk
    restart: always
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/studentdb
      - SPRING_DATASOURCE_USERNAME=Nuha
      - SPRING_DATASOURCE_PASSWORD=123
    volumes:
      - ./spring/spring.jar:/app/spring.jar
    command: java -jar /app/spring.jar
    depends_on:
      - db
 
