version: "3.9"

services:
  web:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./html:/usr/share/nginx/html

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: studentdb
      MYSQL_USER: Nuha
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

